### ISSUE TITLE
can you provide binary files for people who don't use arch?

### ISSUE THREAD

**Issue by waltzforvenus** [aunali1/linux-mbp-arch#11]

**Comment by aunali1** [comment]
Do you have a specific use case in mind? This kernel uses Arch Linux specific upstream patches and AFAIK most distros apply their own patches for their respective kernel variants to better mesh with their packaging schemes.

**Comment by waltzforvenus** [comment]
Wanted to use it with debian but I guess that doesn't seem possible, also while making an archiso the repository was giving weird errors so having it available to download would be nice.

**Comment by SentToDevNull** [comment]
@peryngveohlin666 If you don't want to use Arch, one option is Gentoo. With aunali's patches, you can spin up a working kernel pretty easily, and you can have the patches auto-applied to every new version of the kernel (though this may break in the future).

**Comment by 74th** [comment]
for Ubuntu/Mint/Debian https://github.com/marcosfad/mbp-ubuntu-kernel

**Comment by aunali1** [comment]
@peryngveohlin666 For more information regarding the current supported distros, please visit http://wiki.t2linux.org/
