### ISSUE TITLE
Invalid signature for linux-mbp packages

### ISSUE THREAD

**Issue by leondzn** [aunali1/linux-mbp-arch#14]
I could not proceed with the ISO build since it couldn't verify the `linux-mpb` and `linux-mbp-headers` packages.

There also seems to be an issue with the repo server as the download keeps on getting cut-off and I had to retry the download multiple times.

**Comment by aunali1** [comment]
Hi @leondzn! Yes I am aware of the issues with the packages site, hopefully soon i'll be moving the files to a global CDN provider resolving most of these problems.

**Comment by MatthiasPortzel** [comment]
Seconding. It appears the key.asc file is no longer hosted, which means I can’t install any of these packages.

Edit: I added `SigLevel = Never` to `/etc/pacman.conf` to disable all cert checking and was able to install these packages, and then change it back.

**Comment by aunali1** [comment]
@leondzn @MatthiasSaihttam Please use the new repo location at http://dl.t2linux.org.
