### ISSUE TITLE
Can't download: OpenSSL SSL_Read: SSL_ERROR_SYSCALL, errno 104

### ISSUE THREAD

**Issue by TRPB** [aunali1/linux-mbp-arch#2]
This happens with wget, firefox and pacman. Unfortunately there seems to be an SSL error on your server.

I can use wget to get it, but unfortunately not pacman which makes the repository not work as intended. 

wget log:

```
linux-mbp-5.2.14-3-x86_64.pkg.tar.xz                  76%[++++++++++++++++++++++++++==============================================================>                           ]  55.86M  4.64MB/s    in 7.9s    

2019-09-16 16:55:46 (4.99 MB/s) - Read error at byte 58574290/76319228 (Error in the pull function.). Retrying.
```

I've tried from my PC running arch and the macbook pro, I'm trying to install the kernel on. I'm not sure what the issue is but there's some kind of SSL error

edit: wget even needs tries=inf as the default of 20 is not enough. It keeps getting disconnected.

**Comment by aunali1** [comment]
@TRPB This is highly unusual. I made some modifications to relax SSL timeout enforcement delays. Can you please try again?

**Comment by TRPB** [comment]
That's fixed it, I can now download it with wget and pacman, thanks.
