### ISSUE TITLE
any chance of an update?

### ISSUE THREAD

**Issue by TRPB** [aunali1/linux-mbp-arch#20]
Unfortunately, I can't build virtualbox-host-dkms with this kernel, is is possible to update this to the latest kernel? Or do the patches need updating to do that? 

edit: It looks like a simple rebuild will work

https://forums.gentoo.org/viewtopic-t-905516-start-0.html

**Comment by aunali1** [comment]
Yep, also please update to the new repo located at http://dl.t2linux.org. The old site has been deprecated.

**Comment by aunali1** [comment]
@TRPB Please upgrade now, and close the issue accordingly.

**Comment by TRPB** [comment]
Thanks for the quick update!
