### ISSUE TITLE
Can’t boot to the kernel

### ISSUE THREAD

**Issue by Ahmed97i** [aunali1/linux-mbp-arch#21]
I installed the kernel using makepkg-si then mkinitcpio -p Linux-mbp but when i boot using refind it dropped me to emergency shell any help will be appreciated

**Comment by aunali1** [comment]
@Ahmed97i I suggest that you not use refind, as it tends to mess with block device UUIDs. If you know the `/dev/nvme0n1pX` number, then you can temporarily provide the rootfs as a boot arg to refind as such `root=/dev/nvme0n1pX`.

**Comment by Ahmed97i** [comment]
@aunali1 you are right I will try that on refind-linux.conf because I cannot use grub it ends with errors when I try refind and it fails I will tell you the errors I get with grub thank you

**Comment by Ahmed97i** [comment]
![image](https://user-images.githubusercontent.com/71390035/93659180-509a4480-fa4b-11ea-96cd-17ba7ee886a8.jpeg)
![image](https://user-images.githubusercontent.com/71390035/93659187-5e4fca00-fa4b-11ea-9324-cb50a331fec7.jpeg)
![Uploading 93659192...]
![Uploading 93659194...]
![Uploading 93659196...]
I get these when I try to install grub 
After downloading the Linux kernel then mkinitcpio -p Linux 
Then I type grub-install --target=x86_64-efi --bootloader-id=grub_uefi --recheck I end up with these errors

**Comment by Ahmed97i** [comment]
![image](https://user-images.githubusercontent.com/71390035/93659294-57758700-fa4c-11ea-8bf6-61caf1991372.jpeg)

**Comment by Ahmed97i** [comment]
After working on it now I have this error ![image](https://user-images.githubusercontent.com/71390035/93659713-fdc38b80-fa50-11ea-9852-61c84a4973f9.jpeg)

**Comment by Ahmed97i** [comment]
After formatting the efi partition with mkfs.fat -s1 -F32 /dev/nvme0n1p3 (I had to reduce cluster size otherwise I had error:not enough cluster size for 32-bit fat) the previous error popped up.
FYI: the fstab file does not include my efi partition even though I mounted the efi partition at boot/EFI and regenerate fstab
![image](https://user-images.githubusercontent.com/71390035/93660380-ebe4e700-fa56-11ea-9574-efab6eae1028.jpeg)
![image](https://user-images.githubusercontent.com/71390035/93667573-b0b2da00-fa8f-11ea-9db3-08c1aeb9005f.jpeg)
