### ISSUE TITLE
Keyboard still not working on Linux-mbp kernel

### ISSUE THREAD

**Issue by Ahmed97i** [aunali1/linux-mbp-arch#22]

**Comment by aunali1** [comment]
@Ahmed97i I can not help you if you don't give me any details about your device.

**Comment by Ahmed97i** [comment]
I apologise because i didn't provide you with information. I'm on it I thing I have a problem at my end once I finish doing by best to solve the problem I will provide you with information about what I did if it fails thank you very much @aunali1

**Comment by tobiwild** [comment]
I can reproduce this with kernel `5.8.10`. Keyboard with `5.7.17` works fine. With `5.8.10` I get the following error:
```
kernel: bce-vhci: Possible desync, cmd cancel timed out
```

Hardware is MacBookPro16,1

**Comment by Ahmed97i** [comment]
I finally booted into Linux-mbp kernel but the keyboard is still non-functional!!?
 ![image](https://user-images.githubusercontent.com/71390035/93693209-80a61e00-fb05-11ea-8cc5-5a3c38ce4142.jpeg)

**Comment by aunali1** [comment]
@Ahmed97i You need to install the `apple-bce` kernel module found at https://github.com/aunali1/apple-bce-arch. Aside from that, i suggest that you use the binary repo at http://dl.t2linux.org/archlinux/mbp/x86_64/index.html.

**Comment by Ahmed97i** [comment]
Thank you very much for that I really want to use arch Linux on my Mac

**Comment by Ahmed97i** [comment]
I did what you told me... I installed Apple-bce-arch twice and installed every repo from the link but the keyboard doesn't work. I attempted systemctl apple-bce but to not avail... @aunali1 I really need your help thanks in advance 
FYI: when I try mkinitcpio -p linux- mbp an error appears hope it will help to resolve my issue also dkms status shows the following 
 ![image](https://user-images.githubusercontent.com/71390035/93707338-02ae3b00-fb36-11ea-92bf-05cec5d5e45f.jpeg) 
![image](https://user-images.githubusercontent.com/71390035/93711369-5af53500-fb56-11ea-96b4-a0006bf08866.jpeg)

**Comment by Ahmed97i** [comment]
@aunali1 please help me to sort out my problem...
I have formatted my hard drive installed macOS Catalina added a new partition with ms-Dos format booted up arch installation medium created 3 partitions from newly added one formatted them and mounted them as follows:
/dev/nvme0n1p4 /mnt (root partition ext4)
/dev/nvme0n1p5 /mnt/home 
/dev/nvme0n1p3 /mnt/boot/EFI (F32 partition format type :efi) then I installed Linux kernel booted it up and downloaded your package followed it my makepkg -si --skippgpcheck
Then I removed Linux kernel and booted into Linux-mbp kernel then I 
Installed the kernel module apple-bce and and looked to dkms status it showed Apple-bce is present on linux-mbp kernel when I try to install zst files from the repo you mentioned it came up with the errors in the photo as you see @aunali1 what should I do ?? Please help me! Thanks in advance
![image](https://user-images.githubusercontent.com/71390035/93721321-f65aca00-fb97-11ea-899c-d8819585c579.jpeg)

**Comment by aunali1** [comment]
@Ahmed97i You need to import my package signing key which can be found at http://dl.t2linux.org/archlinux/key.asc. Then run the following to import the key.asc:
```
$ pacman-key --add key.asc
$ pacman-key --finger 7F9B8FC29F78B339
$ pacman-key --lsign-key 7F9B8FC29F78B339
```
You can then proceed to install the files. Additionally, you do not need to manually download the files from the site. Simply append the following to your `/etc/pacman.conf` file:
```
[mbp]
Server = http://dl.t2linux.org/archlinux/$repo/$arch
```
Thus, installing the packages is as easy as:
```
$ pacman -S linux-mbp linux-mbp-headers apple-bce-git
```
**NOTE:** Only install either the `apple-bce-git` or `apple-bce-dkms-git` packages, not both. The former is a binary compiled against the current `linux-mbp` release, whereas the latter bundles the source and use the `dkms` program to compile the module against the available kernels.

**Comment by Ahmed97i** [comment]
@aunali1 I used wget package to download the key.asc then followed the commands you typed and installed Apple-bce-git unfortunately my keyboard is still not working 
Dkms status shows nothing what else can I do!?? 
![image](https://user-images.githubusercontent.com/71390035/93723310-42ad0680-fba6-11ea-99a4-e7b5081fe9dd.jpeg)

**Comment by Ahmed97i** [comment]
I get this error
![image](https://user-images.githubusercontent.com/71390035/93723444-45f4c200-fba7-11ea-955c-a8f351ba5d66.png)

**Comment by aunali1** [comment]
@Ahmed97i Installing the package simply installs the binary in the proper location. You will need to load the `apple-bce` module as well for it to properly register the device, which can be achieved with the following:
```
$ sudo modprobe apple-bce
```

**Comment by Ahmed97i** [comment]
I'm seeing this is it ok?? Should I wait until it finishes??
![Uploading 93723638...]

**Comment by Ahmed97i** [comment]
Is this ok??
![image](https://user-images.githubusercontent.com/71390035/93723651-16df5000-fba9-11ea-85cf-80238cc79436.jpeg)

**Comment by aunali1** [comment]
@Ahmed97i No thats no good, you need to make sure to load `apple-bce` before any of the other modules. Specify it in the `/etc/mkinitcpio.conf` file with the `MODULES` tag. Then rebuild your initcpio image as follows:
```
$ sudo mkinitcpio -p linux-mbp
```
Then proceed to reboot.

**Comment by Ahmed97i** [comment]
@aunali1 you are awesome thank you very much it worked!!!!! I really don't know how to thank you

**Comment by aunali1** [comment]
@Ahmed97i Sure, please do close both of your issues though.
