### ISSUE TITLE
A bit of help with touchbar issue please

### ISSUE THREAD

**Issue by Ahmed97i** [aunali1/linux-mbp-arch#23]
@aunali1 I'm very thankful to you for kind help with keyboard and touchpad. But unfortunately I found that my touchbar is not working so I did the followings 

git clone https://github.com/roadrunner2/macbook12-spi-driver.git /usr/src/apple-ibridge-0.1

dkms install -m apple-ibridge -v 0.1

modprobe apple-ib-tb
modprobe apple-ib-als

I also tagged Apple-ibridge to mkinitcpio.conf 
Mkinitcpio -p Linux-mbp
Reboot
But that didn't help 
Hope the information here and in the attached photo helps to sort out my problem thanks in advance

**Comment by Ahmed97i** [comment]
![image](https://user-images.githubusercontent.com/71390035/93740072-7150ce80-fbf2-11ea-8bf5-a2c6d17f43b3.jpeg)

**Comment by Ahmed97i** [comment]
I also tried to tag Apple-ib-tb and Apple-ib-als in addition to Apple-ibridge and industrialio-triggered-buffer to mkinitcpio.conf
Mkinitcpio -p linux-mbp
Reboot 
But that also unfortunately did not help @aunali1 what can I do??

**Comment by Ahmed97i** [comment]
I also tried to remove and reinstall the dkms for Apple-ibridge 
I typed:
Sudo dkms install -m apple-ibridge -v 0.1
The results are: 
![image](https://user-images.githubusercontent.com/71390035/93776337-205dcc00-fc2c-11ea-952f-8fecc8298df6.jpeg)

**Comment by Ahmed97i** [comment]
@aunali1 is this order correct?
![image](https://user-images.githubusercontent.com/71390035/93778380-80ee0880-fc2e-11ea-995e-8539b0720df2.jpeg)

**Comment by Ahmed97i** [comment]
I also get this when I try the other way to install the module 
![image](https://user-images.githubusercontent.com/71390035/93781596-353d5e00-fc32-11ea-9069-51408857636e.jpeg)
Any help will be appreciated sorry for taking your time

**Comment by Ahmed97i** [comment]
When I try macbook12-spi-driver-dkms package present in AUR and reboot while mkinitcpio.conf contains applespi beside apple-bce 
I end up with this again 
![image](https://user-images.githubusercontent.com/71390035/93784024-23a98580-fc35-11ea-8ad2-cb957ab71498.jpeg)

**Comment by Ahmed97i** [comment]
Hurray!! I solved it without your help this time 😊☺️

**Comment by truonggiang0710** [comment]
> Hurray!! I solved it without your help this time 😊☺️

How do you resolve it?

**Comment by networkException** [comment]
See https://wiki.t2linux.org/guides/dkms/
