### ISSUE TITLE
Kernel 5.8.10-1: MacbookPro15,2 heating up after boot and eventually freezing

### ISSUE THREAD

**Issue by stefanpartheym** [aunali1/linux-mbp-arch#26]
I updated the kernel version from 5.7.17-1 to 5.8.10-1 today.
After rebooting I noticed that the fans in my mbp were speeding up. After a while (3 minutes or so) my mbp completely freezed and I had to manually shutdown.
Unfortunately I do not have dmesg output for this issue. I immediately switched back to kernel 5.7.17-1 without further investigation.
However, maybe someone else has the same issue and knows whats going on.

**Comment by tobiwild** [comment]
May be related to https://github.com/aunali1/linux-mbp-arch/issues/24, I have the same issue. When I disable `apple-bce`, I experience no freeze.

**Comment by stefanpartheym** [comment]
Ok sorry, this was my mistake.
Due to the fact, that in the past I used the `apple-bce-dkms-git` package, I had no module-autoload configuration in `/etc/modules-load.d`. This wasn't necessary, because dkms was already taking care of loading/unloading the module automatically.
After uninstalling the `apple-bce-dkms-git` package, I now installed the new kernel as well as the non-dkms apple-bce package:
```
pacman -S linux-mbp linux-mbp-docs linux-mbp-headers apple-bce-git
```
I also created a new module-autoload file `/etc/modules-load.d/apple-bce.conf`:
```
apple-bce
```

After rebooting my mbp, everything seems to work now. No heating up, no freeze. :)

**Comment by stefanpartheym** [comment]
Unfortunately, I had to reopen. Now - after rebooting a couple of times - I experience the exact same issue as in #22 and #24 .
dmesg spams `bce_vhci_urb_dequeue: 81` and mbp is again very slow and heating up...
Again downgraded to kernel `5.7.17-1`. Can't see the reason for this issue :(

**Comment by stefanpartheym** [comment]
I can confirm that with the new kernel version 5.10.12-1 everything works as expected. No heating up, no freeze.
Thanks!
