### ISSUE TITLE
can you include bce.ko in your repo?

### ISSUE THREAD

**Issue by TRPB** [aunali1/linux-mbp-arch#3]
Sorry if this isn't the best place to ask but. Currently, each time there's a kernel update, it requires manually rebuilding and updating the bce driver. It would be great if you could also include this in your repo as if you forget, it requires a USB keyboard to rebuild.

**Comment by caioquirino** [comment]
Hi @TRPB, in order to make it easier, I am adding to the bce project a simple dkms config that can autobuild it whenever we change the kernel to make our life easier :)

**Comment by aunali1** [comment]
@caioquirino No need, I have the following AUR packages with their binary counterparts in my [repo](https://packages.aunali1.com/archlinux/mbp/x86_64/).
- `apple-bce-git` - Non-DKMS binary variant which is compiled against my latest stable linux-mbp release. Useful for packaging ISOs as DKMS can cause issues.
- `apple-bce-dkms-git` - DKMS variant of the BCE driver.

The source for these packages can be found at https://github.com/aunali1/apple-bce-arch.

**Comment by caioquirino** [comment]
Hi @aunali1, thank you for the fast and complete answer! Which kind of issue the DKMS can cause? :)
Are we active in the gitter for MBP+Linux? 
I am having some difficulty to debug some issues with my MBP15,* wifi...

**Comment by aunali1** [comment]
> Are we active in the gitter for MBP+Linux?
> I am having some difficulty to debug some issues with my MBP15,* wifi...

Most of the people involved are on the public Discord server, invite [here](https://discord.gg/cnEhve).

**Comment by TRPB** [comment]
I hadn't realised the packages were already up there! Thanks :)
