### ISSUE TITLE
Question: Where did the package repository go?

### ISSUE THREAD

**Issue by stefanpartheym** [aunali1/linux-mbp-arch#31]
Hi, just a quick question: Where did the package repository (http://dl.t2linux.org/archlinux/$repo/$arch) go?
I recently tried to update arch, but the package repo failed to update.

Best regards
Stefan

**Comment by axxapy** [comment]
https://github.com/aunali1/linux-mbp-arch/issues/20#issuecomment-692454012
(I have not tried myself though)

**Comment by JPyke3** [comment]
> [#20 (comment)](https://github.com/aunali1/linux-mbp-arch/issues/20#issuecomment-692454012)
> (I have not tried myself though)

That issue is unrelated to this one. I have received word that it's a CDN issue. He is working on resolving it when possible but is rather busy.

**Comment by aunali1** [comment]
@stefanpartheym The repository should be back up now. Please test and close this issue accordingly.

**Comment by stefanpartheym** [comment]
@aunali1 Huge thanks! I can confirm the repo is up again. Will try the new kernel 5.10.12-1 later ;)
