### ISSUE TITLE
Macbook Pro 2020 4 usb C ports (Macbook Pro 16,2)

### ISSUE THREAD

**Issue by DimitriDokuchaev** [aunali1/linux-mbp-arch#33]
Hello,

I would like to ask if it is possible to add support for the "new" Macbook pro for keyboard and trackpad.

The trackpad as it is doesn't right click.

here are the extracts of lsusb and lspci, if anything else is needed I can provide it.

![IMG_20210113_191953](https://user-images.githubusercontent.com/5759671/104604821-ad161500-5675-11eb-9a10-ca0cb9f1aea5.jpg)

Thank you in advance,
Best regards,
Dimitri

**Comment by asanormie** [comment]
Will piggyback on this to request the same for MBA9,1

**Comment by workcomplete** [comment]
Will piggyback on this to request the same for MBA9,1 2020 but can open a separate issue if preferable. lsusb below.

Cheers.

`Bus 001 Device 007: ID 05ac:8102 Apple, Inc. Touch Bar Backlight
Bus 001 Device 006: ID 05ac:0280 Apple, Inc. Apple Internal Keyboard / Trackpad
Bus 001 Device 005: ID 05ac:8103 Apple, Inc. Headset
Bus 001 Device 004: ID 05ac:8262 Apple, Inc. Ambient Light Sensor
Bus 001 Device 003: ID 05ac:8514 Apple, Inc. FaceTime HD Camera (Built-in)
Bus 001 Device 002: ID 05ac:8233 Apple, Inc. Apple T2 Controller
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 005 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 004 Device 005: ID 0a12:0001 Cambridge Silicon Radio, Ltd Bluetooth Dongle (HCI mode)
Bus 004 Device 008: ID 046d:c077 Logitech, Inc. M105 Optical Mouse
Bus 004 Device 006: ID 045e:07f8 Microsoft Corp. Wired Keyboard 600 (model 1576)
Bus 004 Device 004: ID 05e3:0608 Genesys Logic, Inc. Hub
Bus 004 Device 009: ID 2109:8817 VIA Labs, Inc. 
Bus 004 Device 007: ID 2109:0100 VIA Labs, Inc. USB 2.0 Hub
Bus 004 Device 003: ID 2109:2817 VIA Labs, Inc. USB 2.0 Hub
Bus 004 Device 002: ID 1a40:0801 Terminus Technology Inc. USB 2.0 Hub
Bus 004 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 003 Device 003: ID 0bda:8153 Realtek Semiconductor Corp. RTL8153 Gigabit Ethernet Adapter
Bus 003 Device 002: ID 2109:0817 VIA Labs, Inc. USB3.0 Hub `

**Comment by EmmmaTech** [comment]
I'm a little confused why there are trackpad/keyboard issues with the 16,2. The 16,1 works really well

**Comment by workcomplete** [comment]
Confirming this works on MBA9,1 Thanks @Redecorating @aunali1!

**Comment by workcomplete** [comment]
Don't want to hijack this thread from OP and this is a relatively minor issue, but the keyboard backlight on *MBA9,1* is still not working. The on-screen icon shows up that the keyboard backlight button has been pressed, but the light does not come on. I have also tried the recommendations in the Arch wiki below. I'm running the latest commit of the arch-mbp kernel at time of posting, in Gnome on Wayland.

When using gdbus, the output is stuck at -1
```
[hal@hal ~]$ gdbus call --session --dest org.gnome.SettingsDaemon.Power --object-path /org/gnome/SettingsDaemon/Power --method org.gnome.SettingsDaemon.Power.Keyboard.StepUp
(-1,)
```
When using the D-Bus script provided in the Arch wiki, I get the following error:
```
[hal@hal ~]$ /usr/local/bin/kb-light.py + 1
Traceback (most recent call last):
  File "/usr/local/bin/kb-light.py", line 26, in <module>
    print(kb_light_set(int(sys.argv[2])))
  File "/usr/local/bin/kb-light.py", line 11, in kb_light_set
    current = kbd_backlight.GetBrightness()
  File "/usr/lib/python3.9/site-packages/dbus/proxies.py", line 72, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python3.9/site-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
  File "/usr/lib/python3.9/site-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.UPower.KbdBacklight” on object at path /org/freedesktop/UPower/KbdBacklight
```
I found a resolved version of this error in the forums related to upower, https://bbs.archlinux.org/viewtopic.php?id=240392 but the fix does not apply https://bugs.archlinux.org/task/59984 because there is no such variable  in /usr/lib/systemd/system/upower.service

Anything I could be missing? Could this be an issue with the keyboard backlight usb ID kernel patch?

**Comment by Redecorating** [comment]
There's meant to be a `/sys/class/leds/apple::kbd_backlight` folder, but this isn't present on my MacBookPro16,1 and it's also reported as missing on the MacBookPro16,2.

**Comment by aunali1** [comment]
@workcomplete Please create a separate issue to track this. Closing this one.
