### ISSUE TITLE
Root partition on external (USB) disk not detected after loading initrd

### ISSUE THREAD

**Issue by Vestaia** [aunali1/linux-mbp-arch#36]
The root partition device can not be found during boot; though GRUB resides on the same drive and is able to detect the root partition. In the emergency shell, only the internal drive is listed. Are there additional drivers that need to be baked into the initrd to detect an external drive on USB? A previous install when on MacOS 10.14 worked, now attempting to create a new install after the MacOS 11 update. 
- Macbook Pro 15" 2019 (A1990)

**Comment by aunali1** [comment]
@Vestaia My installation is on an external USB SSD and I am unable to replicate your issue. I would suggest updating to the latest release and trying again,

**Comment by spushkin1** [comment]
Hey, I didn’t want to open a whole issue for this, but I was wondering if there is any comparability with this for 2016/2017 MBPs?

**Comment by enx1998** [comment]
Hi @Vestaia have you found the solution to your issue? I have the same problem but only with some kernel verison (I have applied the same configuration).
Thanks ENx

**Comment by Vestaia** [comment]
Yes @enx1998, some hooks were failing to be loaded with `autodetect`. Regenerated the initrd with manual configuration (I don't remember which were needed).
