### ISSUE TITLE
brcmf_run_escan: error (-5)

### ISSUE THREAD

**Issue by aqw00** [aunali1/linux-mbp-arch#44]
Hi,

I followed the tutorial on [https://t2linux.org/](url) but I'm stuck in the instalation of Arch.
Get errors and I can't connect or scan my wifi with iwctl I tried even just the command.
`$ iwctl --passphrase passphrase station device connect SSID`
but didn't work my errors are.
`[1814.538323] ieee80211 phy0: brcmf_msgbuf_query_dcmd: Timeout on response for query command`
`[1814.538443] ieee80211 phy0: brcmf_run_escan: error (-5)`
`[1814.538511] ieee80211 phy0: brcmf_cfg80211_scan: scan error (-5)`
I have a macbook air 2020

**Comment by networkException** [comment]
Please raise this issue in the [wiki repository](https://github.com/t2linux/wiki) or on [discord](https://discord.com/invite/68MRhQu)
