### ISSUE TITLE
Cannot be downloaded from repository, Error 522, Connection timeout

### ISSUE THREAD

**Issue by OneeTheOne** [aunali1/linux-mbp-arch#5]
Hello,

first of all thanks for the amaizing work you put into this.
Today I encountered an issue when trying to download the compiled kernel from your repository.
The connection simply times out. Tried few machines on different networks but always with the same end.
Even the Build status link is not working. 
Hope this is just a glitch and you are not shutting it down :)

Thanks
O.

![2019-11-05-141133_964x405_scrot](https://user-images.githubusercontent.com/16355637/68210641-3e9be880-ffd6-11e9-9a6f-37ea43533f65.png)

**Comment by aunali1** [comment]
@OneeTheOne Sorry about that just a server outage. Everything should be working now. Lemme know if you have any issues, otherwise please close this issue.

**Comment by OneeTheOne** [comment]
Whoo, it is all up and running again. Thank you!
Closing
